# JPA는 스프링부트에서 데이터 접근을 편리하게 해주는 기능.
spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 sql실행
    defer-datasource-initialization: true